#!/usr/bin/env python3

import argparse
import json
import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RUST_LOG = "info,hyper=warn,reqwest=warn"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a live single-validator deployment bundle for gossip_protocol."
    )
    parser.add_argument("output_dir", type=Path, help="Empty directory for the generated bundle.")
    parser.add_argument(
        "--public-host",
        required=True,
        help="Public hostname that will front the validator through nginx.",
    )
    parser.add_argument(
        "--bind",
        default="127.0.0.1:9001",
        help="Node bind address for the local validator process.",
    )
    parser.add_argument(
        "--build-profile",
        choices=["debug", "release"],
        default="release",
        help="Cargo profile used to build the validator binary.",
    )
    parser.add_argument(
        "--wallet-passphrase-env",
        default="GOSSIP_PROTOCOL_WALLET_PASSPHRASE",
        help="Environment variable holding the validator and requester wallet passphrase.",
    )
    parser.add_argument(
        "--requester-airdrop",
        default="10",
        help="Initial HT airdrop for the generated requester wallet.",
    )
    parser.add_argument(
        "--block-time-secs",
        type=int,
        default=5,
        help="Block interval written into genesis.json.",
    )
    parser.add_argument(
        "--chain-id",
        help="Optional explicit chain ID. Default: generated by the CLI.",
    )
    parser.add_argument(
        "--peer-allow",
        action="append",
        default=[],
        help="Repeatable peer IP or CIDR allowed to reach /v1/internal/* through nginx.",
    )
    parser.add_argument(
        "--control-api-token",
        help="Optional control API bearer token. Default: generated securely.",
    )
    parser.add_argument(
        "--gossip-api-token",
        help="Optional gossip API bearer token. Default: generated securely.",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Reuse the existing built binary instead of running cargo build.",
    )
    return parser.parse_args()


def run_cmd(args: list[str], env: dict[str, str], capture_json: bool = False) -> str | dict:
    completed = subprocess.run(
        args,
        cwd=REPO_ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed ({completed.returncode}): {' '.join(args)}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    stdout = completed.stdout.strip()
    if capture_json:
        return json.loads(stdout)
    return stdout


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def ensure_empty_output_dir(path: Path) -> None:
    if path.exists():
        if not path.is_dir():
            raise RuntimeError(f"{path} exists and is not a directory")
        if any(path.iterdir()):
            raise RuntimeError(f"{path} must be empty")
    else:
        path.mkdir(parents=True)


def build_binary(profile: str, skip_build: bool, env: dict[str, str]) -> Path:
    if not skip_build:
        args = ["cargo", "build"]
        if profile == "release":
            args.append("--release")
        subprocess.run(args, cwd=REPO_ROOT, env=env, check=True)
    binary = REPO_ROOT / "target" / profile / "gossip_protocol"
    if not binary.exists():
        raise RuntimeError(f"expected built binary at {binary}")
    return binary


def write_text(path: Path, contents: str, mode: int) -> None:
    path.write_text(contents, encoding="utf-8")
    os.chmod(path, mode)


def parse_bind(bind: str) -> tuple[str, str]:
    if ":" not in bind:
        raise RuntimeError("--bind must use HOST:PORT format")
    host, port = bind.rsplit(":", 1)
    if not host or not port:
        raise RuntimeError("--bind must use HOST:PORT format")
    return host, port


def nginx_upstream_host(bind_host: str) -> str:
    if bind_host in {"0.0.0.0", "::"}:
        return "127.0.0.1"
    return bind_host


def render_node_env(
    passphrase_env: str,
    passphrase_value: str,
    control_api_token: str,
    gossip_api_token: str,
) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by scripts/bootstrap_first_validator.py\n"
        "set -a\n"
        f"export {passphrase_env}={shell_quote(passphrase_value)}\n"
        f"export GOSSIP_PROTOCOL_CONTROL_API_TOKEN={shell_quote(control_api_token)}\n"
        f"export GOSSIP_PROTOCOL_GOSSIP_API_TOKEN={shell_quote(gossip_api_token)}\n"
        f"export RUST_LOG={shell_quote(DEFAULT_RUST_LOG)}\n"
        "set +a\n"
    )


def render_run_script(
    env_path: Path,
    binary_path: Path,
    validator_wallet: Path,
    genesis_path: Path,
    state_dir: Path,
    bind: str,
) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

source {shell_quote(str(env_path))}

exec {shell_quote(str(binary_path))} node run \\
  --wallet {shell_quote(str(validator_wallet))} \\
  --wallet-passphrase-env GOSSIP_PROTOCOL_WALLET_PASSPHRASE \\
  --genesis {shell_quote(str(genesis_path))} \\
  --state-dir {shell_quote(str(state_dir))} \\
  --bind {shell_quote(bind)} \\
  --control-api-token "$GOSSIP_PROTOCOL_CONTROL_API_TOKEN" \\
  --gossip-api-token "$GOSSIP_PROTOCOL_GOSSIP_API_TOKEN"
"""


def render_status_script(public_host: str, bind: str) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

mode="${{1:-public}}"

case "$mode" in
  local)
    url=http://{bind}/v1/control/status
    ;;
  public)
    url=https://{public_host}/v1/control/status
    ;;
  *)
    echo "usage: $0 [local|public]" >&2
    exit 1
    ;;
esac

curl --fail --silent --show-error "$url" | python3 -m json.tool
"""


def render_submit_script(
    env_path: Path,
    binary_path: Path,
    requester_wallet: Path,
    bind: str,
) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <health-url> [extra health-check args...]" >&2
  exit 1
fi

url="$1"
shift

source {shell_quote(str(env_path))}

exec {shell_quote(str(binary_path))} tx health-check \\
  --wallet {shell_quote(str(requester_wallet))} \\
  --wallet-passphrase-env GOSSIP_PROTOCOL_WALLET_PASSPHRASE \\
  --node {shell_quote(f"http://{bind}")} \\
  --api-token "$GOSSIP_PROTOCOL_CONTROL_API_TOKEN" \\
  --url "$url" \\
  "$@"
"""


def render_systemd_unit(bundle_dir: Path, run_script: Path) -> str:
    return f"""[Unit]
Description=gossip_protocol first validator
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={bundle_dir}
ExecStart=/usr/bin/env bash {run_script}
Restart=always
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths={bundle_dir / "state"} {bundle_dir / "logs"}
StandardOutput=append:{bundle_dir / "logs" / "validator.log"}
StandardError=append:{bundle_dir / "logs" / "validator.log"}

[Install]
WantedBy=multi-user.target
"""


def render_nginx_conf(
    public_host: str,
    upstream_host: str,
    upstream_port: str,
    peer_allowlist: list[str],
) -> str:
    if peer_allowlist:
        allow_lines = "\n".join(f"        allow {entry};" for entry in peer_allowlist)
    else:
        allow_lines = (
            "        # No peers are currently allowed.\n"
            "        # Add `allow <peer-ip-or-cidr>;` lines here before expanding beyond one validator."
        )

    proxy_lines = (
        f"        proxy_pass http://{upstream_host}:{upstream_port};\n"
        "        proxy_http_version 1.1;\n"
        "        proxy_set_header Host $host;\n"
        "        proxy_set_header X-Real-IP $remote_addr;\n"
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "        proxy_set_header X-Forwarded-Proto $scheme;"
    )

    return f"""# Generated by scripts/bootstrap_first_validator.py
# Replace the certificate paths with your real TLS material before enabling.

limit_req_zone $binary_remote_addr zone=health_submit:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=health_quote:10m rate=10r/s;

server {{
    listen 443 ssl http2;
    server_name {public_host};

    ssl_certificate /etc/letsencrypt/live/{public_host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{public_host}/privkey.pem;

    client_max_body_size 64k;
    proxy_read_timeout 30s;
    proxy_connect_timeout 5s;
    proxy_send_timeout 30s;

    location /v1/control/status {{
{proxy_lines}
    }}

    location /v1/control/account/ {{
{proxy_lines}
    }}

    location /v1/control/ledger {{
{proxy_lines}
    }}

    location /v1/control/jobs/ {{
{proxy_lines}
    }}

    location /v1/control/swaps/ {{
{proxy_lines}
    }}

    location /v1/control/adapters {{
{proxy_lines}
    }}

    location = /v1/control/submit {{
        limit_req zone=health_submit burst=20 nodelay;
{proxy_lines}
    }}

    location = /v1/control/swap/quote {{
        limit_req zone=health_quote burst=40 nodelay;
{proxy_lines}
    }}

    location /v1/internal/ {{
{allow_lines}
        deny all;
{proxy_lines}
    }}
}}
"""


def render_summary(
    bundle_dir: Path,
    public_host: str,
    bind: str,
    chain_id: str,
    validator_address: str,
    requester_address: str,
) -> str:
    return f"""# First Validator Live Bundle

Bundle root: `{bundle_dir}`
Public host: `{public_host}`
Local bind: `{bind}`
Chain ID: `{chain_id}`
Validator address: `{validator_address}`
Requester address: `{requester_address}`

Generated files:

- `bin/gossip_protocol`: copied binary
- `wallets/validator.json`: encrypted validator wallet
- `wallets/requester.json`: encrypted requester wallet with initial HT
- `config/genesis.json`: single-validator genesis
- `config/node.env`: shell env file containing tokens and wallet passphrase
- `run-validator.sh`: foreground launcher for the validator node
- `systemd/gossip-protocol-validator.service`: service unit referencing this bundle
- `nginx/gossip_protocol.conf`: TLS and rate-limit edge config
- `submit-health-check.sh`: helper for paid health checks from the requester wallet
- `check-status.sh`: helper for checking public node status

Recommended next steps:

1. Review `config/node.env` and rotate tokens if you do not want the generated defaults.
2. Review `nginx/gossip_protocol.conf`, install real TLS cert paths, and add peer allowlist entries before adding more validators.
3. Copy `systemd/gossip-protocol-validator.service` into `/etc/systemd/system/`.
4. Start the node with `sudo systemctl daemon-reload && sudo systemctl enable --now gossip-protocol-validator`.
5. Verify the live edge with `./check-status.sh`.
6. Submit the first paid health check with `./submit-health-check.sh https://example.com/health --expect-status 200`.
"""


def main() -> int:
    args = parse_args()

    passphrase_value = os.environ.get(args.wallet_passphrase_env)
    if not passphrase_value:
        raise RuntimeError(
            f"missing required environment variable {args.wallet_passphrase_env}"
        )

    ensure_empty_output_dir(args.output_dir)

    env = os.environ.copy()
    env[args.wallet_passphrase_env] = passphrase_value

    binary = build_binary(args.build_profile, args.skip_build, env)

    bind_host, bind_port = parse_bind(args.bind)
    upstream_host = nginx_upstream_host(bind_host)

    bundle_dir = args.output_dir.resolve()
    bin_dir = bundle_dir / "bin"
    wallets_dir = bundle_dir / "wallets"
    config_dir = bundle_dir / "config"
    state_dir = bundle_dir / "state"
    logs_dir = bundle_dir / "logs"
    systemd_dir = bundle_dir / "systemd"
    nginx_dir = bundle_dir / "nginx"

    for directory in [bin_dir, wallets_dir, config_dir, state_dir, logs_dir, systemd_dir, nginx_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    shipped_binary = bin_dir / "gossip_protocol"
    shutil.copy2(binary, shipped_binary)
    os.chmod(shipped_binary, 0o755)

    validator_wallet = wallets_dir / "validator.json"
    requester_wallet = wallets_dir / "requester.json"
    genesis_path = config_dir / "genesis.json"
    env_path = config_dir / "node.env"
    run_script = bundle_dir / "run-validator.sh"
    submit_script = bundle_dir / "submit-health-check.sh"
    status_script = bundle_dir / "check-status.sh"
    service_path = systemd_dir / "gossip-protocol-validator.service"
    nginx_path = nginx_dir / "gossip_protocol.conf"
    summary_path = bundle_dir / "BOOTSTRAP_SUMMARY.md"

    run_cmd(
        [
            str(shipped_binary),
            "wallet",
            "create",
            str(validator_wallet),
            "--passphrase-env",
            args.wallet_passphrase_env,
        ],
        env,
        capture_json=True,
    )
    run_cmd(
        [
            str(shipped_binary),
            "wallet",
            "create",
            str(requester_wallet),
            "--passphrase-env",
            args.wallet_passphrase_env,
        ],
        env,
        capture_json=True,
    )

    validator_address = run_cmd(
        [str(shipped_binary), "wallet", "address", str(validator_wallet)],
        env,
    )
    requester_address = run_cmd(
        [str(shipped_binary), "wallet", "address", str(requester_wallet)],
        env,
    )

    genesis_args = [
        str(shipped_binary),
        "genesis",
        "create",
        "--out",
        str(genesis_path),
        "--validator-wallet",
        str(validator_wallet),
        "--airdrop",
        f"{requester_address}={args.requester_airdrop}",
        "--block-time-secs",
        str(args.block_time_secs),
    ]
    if args.chain_id:
        genesis_args.extend(["--chain-id", args.chain_id])
    genesis = run_cmd(genesis_args, env, capture_json=True)

    control_api_token = args.control_api_token or secrets.token_hex(32)
    gossip_api_token = args.gossip_api_token or secrets.token_hex(32)

    write_text(
        env_path,
        render_node_env(
            args.wallet_passphrase_env,
            passphrase_value,
            control_api_token,
            gossip_api_token,
        ),
        0o600,
    )
    write_text(
        run_script,
        render_run_script(
            env_path,
            shipped_binary,
            validator_wallet,
            genesis_path,
            state_dir,
            args.bind,
        ),
        0o755,
    )
    write_text(status_script, render_status_script(args.public_host, args.bind), 0o755)
    write_text(
        submit_script,
        render_submit_script(env_path, shipped_binary, requester_wallet, args.bind),
        0o755,
    )
    write_text(service_path, render_systemd_unit(bundle_dir, run_script), 0o644)
    write_text(
        nginx_path,
        render_nginx_conf(args.public_host, upstream_host, bind_port, args.peer_allow),
        0o644,
    )
    write_text(
        summary_path,
        render_summary(
            bundle_dir,
            args.public_host,
            args.bind,
            genesis["chain_id"],
            validator_address,
            requester_address,
        ),
        0o644,
    )

    print(
        json.dumps(
            {
                "bundle_dir": str(bundle_dir),
                "binary_path": str(shipped_binary),
                "genesis_path": str(genesis_path),
                "env_path": str(env_path),
                "run_script": str(run_script),
                "systemd_unit": str(service_path),
                "nginx_conf": str(nginx_path),
                "chain_id": genesis["chain_id"],
                "validator_address": validator_address,
                "requester_address": requester_address,
                "min_health_receipts": genesis["min_health_receipts"],
                "public_host": args.public_host,
                "bind": args.bind,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
